import { Inter } from "@next/font/google";
import Head from "next/head";
import Banner from "./Home/Banner";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className="">
            <Banner />
          </div>
        </div>
      </main>
    </div>
  );
}
